### ISSUE TITLE
NoSuchEntity should indicate which entity

### ISSUE THREAD

**Issue by drewcrawford** [AnarchyTools/atfoundation#9]
One of the annoyances I have with atfoundation at present is that I get errors of the form

```
fatal error: 'try!' expression unexpectedly raised an error: atfoundation.SysError.NoSuchEntity: file /Users/drew/Code/swift-osx/swift/stdlib/public/core/ErrorType.swift, line 53
```

Probably, somewhere in my code builds a silly path, but what silly path does it build, and where should I look?  The error is not useful.

IMO in such cases, we should print which path cannot be found.

**Comment by dunkelstern** [comment]
Yeah that's probably right, i'll see what extra information i'll put on the SysError type.

**Comment by drewcrawford** [comment]
I tried to test `develop` branch today, but it fails to build on swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a.  Maybe take a look at the the PR #10  and backport onto develop branch?

**Comment by dunkelstern** [comment]
Ok merged PR #10 and updated develop

**Comment by drewcrawford** [comment]
develop doesn't cause any major breaks that I can detect.  LGTM

**Comment by drewcrawford** [comment]
FYI, we have several packages interested in taking this feature.

**Comment by dunkelstern** [comment]
Merged, closing this issue
